// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ORM.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Document", b =>
                {
                    b.Property<int>("DocumentCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DocumentCode"));

                    b.Property<int>("InventoryCode")
                        .HasColumnType("integer");

                    b.Property<int>("ReadingRoomCode")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("DocumentCode")
                        .HasName("document_code");

                    b.HasIndex("InventoryCode");

                    b.HasIndex("ReadingRoomCode");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("Domain.Inventory", b =>
                {
                    b.Property<int>("InventoryCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InventoryCode"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("InventoryCode")
                        .HasName("inventory_code");

                    b.ToTable("inventories", (string)null);
                });

            modelBuilder.Entity("Domain.ReadingRoom", b =>
                {
                    b.Property<int>("ReadingRoomCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReadingRoomCode"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("ReadingRoomCode")
                        .HasName("reading_room_code");

                    b.ToTable("reading_rooms", (string)null);
                });

            modelBuilder.Entity("Domain.Document", b =>
                {
                    b.HasOne("Domain.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_documents_inventories");

                    b.HasOne("Domain.ReadingRoom", "ReadingRoom")
                        .WithMany()
                        .HasForeignKey("ReadingRoomCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_documents_reading_rooms");

                    b.Navigation("Inventory");

                    b.Navigation("ReadingRoom");
                });
#pragma warning restore 612, 618
        }
    }
}
